- mhn/api/views.py
- mhn/static/registration.txt
This change adds the ability to retrieve server information by UUID via the API.
I also added a validation piece in registration.txt to determine if a server had been previously registered. I'm definitely not a bash scripter, so I highly recommend checking my work.
> Modified CHN-Server API and registration script

- collector.run
Signed-off-by: Christopher Collins <collins.christopher@gmail.com>
> fixing unending loop of collector registration

- collector_v2.py
- mhn/common/testcommon.py
- uwsgi.run.j2
- vars/default.yml
Added options to accommodate changes to hpfeeds to allow users to specify MongoDB host and port.
> Added options to allow specification of MongoDB host and port

- celery-beat.run
- celery-worker.run.j2
- nginx.run
- uwsgi.run.j2
* Removed the temporary mongodb helper fix from the uwsgi.run since Alex has merged his changes
* Added some pidfile management to celery_beat.run to hopefully prevent pid issues.
> Pidfile fix & tmp fix removal

- collector.run
- mhn/templates/base.html
Changed the header and footer in the template to remove threatstream branding, focus more on OpenSource.
Also includes fix to persist collector registration
> Removed MHN/Threatstream branding & persisting collector

- nginx.run
- requirements.txt
Grab fixes for Nginx logfile creation
FIxes #28
> Merge from staging

- initdatabase.py
Adding CLI tool for user create, check for DB before init new db
> Adding CLI tool for user create, check for DB before init new db

- initdatabase.py
Checking existence of database tables as test for db initialization or not
> Fix exception if database not initialized

- chnserver.sysconfig
- mhn/templates/ui/attacks.html
- uwsgi.run.j2
To address [issue 49](https://github.com/CommunityHoneyNetwork/CHN-Server/issues/49) regarding timestamp display
> Add UTC to labels to indicate that dates and times are UTC format

- mhn/__init__.py
- mhn/templates/ui/script.html
- scripts/deploy_amun.sh
- scripts/deploy_conpot.sh
- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
- scripts/deploy_glastopf.sh
- scripts/deploy_rdphoney.sh
- scripts/deploy_wordpot.sh
This commit adds (back) the deployment scripts options, but based on the docker model used in CHN
> Stored scripts feature

- chnctl.py
- generateconfig.py
- initdatabase.py
- manage.py
- mhn/__init__.py
- mhn/api/__init__.py
- mhn/api/decorators.py
- mhn/api/models.py
- mhn/api/tests.py
- mhn/api/views.py
- mhn/auth/__init__.py
- mhn/auth/models.py
- mhn/auth/views.py
- mhn/common/clio.py
- mhn/common/ruleutils.py
- mhn/common/testcommon.py
- mhn/common/utils.py
- mhn/static/hpfeeds.py
- mhn/static/ihandlers.py
- mhn/tasks/__init__.py
- mhn/tasks/rules.py
- mhn/ui/utils.py
- mhn/ui/views.py
This should make the code pep8 compatible.  As a side effect, it'll pretty much be python3 ready too, although I haven't tested that.  Would love for someone else to get a good set of eyes on here and make sure I'm not doing something stupid.  Thanks!
> Make pep8 compatible

- .gitlab-ci.yml
Adding in Gitlab CI bits. This adds the static code scanning, linting, and all that other fun stuff
> Feature Enable Gitlab CI

- mhn/__init__.py
- scripts/deploy_amun.sh
- scripts/deploy_conpot.sh
- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
- scripts/deploy_glastopf.sh
- scripts/deploy_rdphoney.sh
- scripts/deploy_wordpot.sh
This changes what the deployment scripts echo to the terminal after execution.
> Editing scripts to change instructions on deployment scripts

- scripts/deploy_amun.sh
- scripts/deploy_conpot.sh
- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
- scripts/deploy_glastopf.sh
- scripts/deploy_rdphoney.sh
- scripts/deploy_wordpot.sh
> In which our hero changes tags and uncomments JSON variables

- requirements.txt
Found there are only two (obvious) uses of requests in the project:
mhn/ui/utils.py
mhn/tasks/rules.py
Both appear to be non-impactful if they did break with the new version, which does not seem likely given the basic usage.
> update requirements for requests vuln

- vars/default.yml
> Update to pull master version of hpfeeds when building

- nginx.run
Reverts CommunityHoneyNetwork/CHN-Server#90 Pulled in too early.
> Revert "Removed nginx startup before certbot run"

- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
> In which our hero updates the deploy scripts to reflect recent changes

- nginx.run
> In which our hero tries to recover from that awful demo that failed

- README.md
> In which our hero standardizes the README.md

- scripts/deploy_amun.sh
- scripts/deploy_conpot.sh
- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
- scripts/deploy_glastopf.sh
- scripts/deploy_rdphoney.sh
- scripts/deploy_uhp.sh
- scripts/deploy_wordpot.sh
I think most people would like the docker containers to auto restart.
> Add auto restart to deploy scripts

- mhn/ui/views.py
I've tried to resolves #122, however there are instances where two blank entries will appear in a list due to the sanitising. My suggestion would be sanitising the data before it's stored by CHN.
> Removes control characters for charts

- config.py.template
- scripts/deploy_amun.sh
- scripts/deploy_conpot.sh
- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
- scripts/deploy_glastopf.sh
- scripts/deploy_rdphoney.sh
- scripts/deploy_uhp.sh
- scripts/deploy_wordpot.sh
This version abstracts the version to a new variable in the scripts, updates it to the pre-release candidate tag, and also fixes a typo.
> Adjust deploy scripts

- scripts/deploy_rdphoney.sh
Fix deploy script for rdphoney for our heros
> Fix deploy script for rdphoney for our heros

- mhn/ui/utils.py
I found using api.ipgeolocationapi.com returned lookups faster and was more accurate than geospray.threatstream.com
> GeoIP API changed

- initdatabase.py
- mhn/__init__.py
- uwsgi.run
This PR will force the superuser password to be reset on every startup to match what's in config.py 
> Extract superuser creation method so it may be called on every startup

- scripts/deploy_big-hp.sh
- scripts/deploy_conpot.sh
- scripts/deploy_cowrie.sh
- scripts/deploy_dionaea.sh
- scripts/deploy_elasticpot.sh
- scripts/deploy_rdphoney.sh
- scripts/deploy_uhp.sh
There may be more, but this is a start.
> Version 1.9.1 prep

- add_remote_credential.sh
- config.py.template
This will enable honeydb to register with the correct channel. There will be a new PR for a deployment script
> Add stub for honeydb honeypot integration

- add_remote_credential.sh
- config.py.template
- mhn/__init__.py
- scripts/deploy_honeydb-agent.sh
> add honeydb-agent support
